version: '3.9'

services:
  nginx:
    image: nginx:1.25.2
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./ssl/cert-key.pem:/etc/nginx/ssl/cert-key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
